llm:
  api_key: "YOUR_API_KEY"

simulation:
  num_agents: 20  # agents
  duration: 50  # time steps
  initial_network_type: "scale_free"  # options: random, scale_free, small_world

agents:
  types:
    - name: "influencer"
      proportion: 0.3
      content_generation_rate: 0.9  # messages per time step
    - name: "casual"
      proportion: 0.7
      content_generation_rate: 0.1  # messages per time step

  personality_traits:
    - openness
    - conscientiousness
    - extraversion
    - agreeableness
    - neuroticism
    - honesty-humility
    - self-efficacy
    - assertiveness
    - distrust
    - emotional stability
    - altruism
    - indifference
    - arrogance
    - curiosity
    - negativity
    - risk-taking
    - sarcasm
    - optimism
    - creativity
    - pessimism
    - empathy
    - cynicism
    - resilience
    - adaptability
    - patience
    - impulsivity
    - independence
    - inflexibility
    - competitiveness
    - trust
    - humor
    - ambition
    - selfishness

content:
  topics:
    - technology
    - science
    - politics
    - sports
    - arts
    - health
    - travel
    - food
    - fashion
    - music
    - movies
    - literature
    - history
    - gaming
    - environment
    - education
    - finance
    - fitness
    - photography
    - entrepreneurship
    - lifestyle
    - psychology
  max_length: 80  # characters

network:
  initial_connections_mean: 5
  initial_connections_std: 2
  connection_update_frequency: 5  # time steps
  agent_invitation_frequency: 6

analysis:
  centrality_measure: "pagerank"  # options: degree, betweenness, pagerank
  community_detection_algorithm: "louvain"
  influencer_threshold: 0.5  # pagerank score
  topic_modeling:
    num_topics: 4
    method: "lda"  # options: lda, nmf

output:
  save_network_snapshots: true
  snapshot_frequency: 5                 # time steps
  save_messages: true
  save_agent_states: true
  save_initial_network_state: false
